public enum RPGTextId
{
	prefix,			// 0 
	usage,			// 1
	help,			// 2
	online,			// 3
	offline,		// 4
	castUsage,		// 5
	castHelp,		// 6
	blinkNoTarget,	// 7
	blinkTooFar,	// 8
	blinkCant,		// 9
	castBlink,		// 10
	viewBlink,		// 11
	castHeal,		// 12
	viewHeal,		// 13
	healFullHealth,	// 14
	magicHelp,		// 15
	magicSpellList,	// 16
	castAscend,		// 17
	viewAscend,		// 18
	failAscend, 	// 19
	castDescend,	// 20
	viewDescend,	// 21
	failDescend,	// 22
	castFireball,	// 23
	viewFireball,	// 24
	failFireball,	// 25
}
